FROM elixirbase:latest

ENV MIX_ENV=dev

COPY . /<%= @app %>
WORKDIR /<%= @app %>

RUN mix deps.get
RUN mix compile
CMD mix app.start

FROM elixircache:latest

ENV MIX_ENV=dev

COPY . /<%= @app %>
COPY --from=elixircache:latest /<%= @app %>/_build /<%= @app %>/dep[s] /<%= @app %>/mix.loc[k] /<%= @app %>
WORKDIR /<%= @app %>

RUN mix deps.get
RUN mix compile
CMD mix app.start
